// Espelha o enum OfferStatus do schema Prisma (packages/database/prisma/schema.prisma).
// Mantido aqui também para uso em código que não importa o Prisma Client (ex.: admin-panel).
export const OFFER_STATUS = {
  RECEBIDO: "RECEBIDO",
  PROCESSANDO_TELEFONE: "PROCESSANDO_TELEFONE",
  TELEFONE_ATUALIZADO: "TELEFONE_ATUALIZADO",
  VALIDANDO_WHATSAPP: "VALIDANDO_WHATSAPP",
  WHATSAPP_VALIDADO: "WHATSAPP_VALIDADO",
  AGUARDANDO_ROTEAMENTO: "AGUARDANDO_ROTEAMENTO",
  AGUARDANDO_ENVIO: "AGUARDANDO_ENVIO",
  EM_PROCESSAMENTO_ENVIO: "EM_PROCESSAMENTO_ENVIO",
  ENVIADO: "ENVIADO",
  SEM_WHATSAPP: "SEM_WHATSAPP",
  SEM_ROTA_CONFIGURADA: "SEM_ROTA_CONFIGURADA",
  ERRO_TELEFONE: "ERRO_TELEFONE",
  ERRO_VALIDACAO_WHATSAPP: "ERRO_VALIDACAO_WHATSAPP",
  ERRO_ENVIO: "ERRO_ENVIO",
  CANCELADO: "CANCELADO",
  EXPIRADO: "EXPIRADO",
} as const;

export type OfferStatus = (typeof OFFER_STATUS)[keyof typeof OFFER_STATUS];

// Estados terminais — oferta não deve mais ser processada por nenhum worker.
export const TERMINAL_STATUSES: OfferStatus[] = [
  OFFER_STATUS.ENVIADO,
  OFFER_STATUS.SEM_WHATSAPP,
  OFFER_STATUS.CANCELADO,
  OFFER_STATUS.EXPIRADO,
];
