-- Correção da corrida de duplicatas (14/09) — o índice funcional criado em
-- 11/09 (idx_offers_webhook_cpf_normalizado) só ACELERAVA a checagem de
-- "mesmo parceiro + mesmo CPF", não IMPEDIA duas requisições simultâneas de
-- passarem pela checagem ao mesmo tempo e criarem 2 ofertas duplicadas (foi
-- exatamente isso que aconteceu: 3 pares de duplicatas encontrados e
-- removidos em produção antes dessa migração, todos com poucos
-- milissegundos de diferença entre si).
--
-- Essa migração cria um ÍNDICE ÚNICO sobre a mesma expressão — vira o alvo
-- do "ON CONFLICT" do novo UPSERT atômico em createOfferIdempotent
-- (prisma-offers-port.ts), que resolve create/reset/descarte numa única ida
-- ao banco. Com um índice ÚNICO, o próprio Postgres garante atomicamente
-- que a corrida não pode mais duplicar, mesmo sob concorrência alta.
--
-- CORREÇÃO (14/09, depois de uma falha real no deploy): CREATE INDEX
-- CONCURRENTLY não pode rodar dentro de uma transação — e o Prisma Migrate
-- só desliga a transação quando a migração inteira tem UM ÚNICO comando
-- (foi assim que a migração 20260911170000, com só esse comando, funcionou
-- antes). Por isso essa migração agora tem SÓ esse comando; o DROP do
-- índice antigo foi movido pra uma migração separada
-- (20260914140000_remove_indice_antigo_cpf_normalizado), senão o Postgres
-- recusa com "CREATE INDEX CONCURRENTLY cannot run inside a transaction
-- block" (foi exatamente esse erro que aconteceu na tentativa anterior,
-- quando os 2 comandos estavam juntos no mesmo arquivo).
CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS "uq_offers_webhook_cpf_normalizado"
ON "offers" ("webhook_id", (regexp_replace("cpf", '\D', '', 'g')));
